name: Update https://test.aitok.us in AWS HK
on:
  workflow_dispatch:

  workflow_call:

jobs:
  update-ecs-service:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-east-1
      - name: Force Update ECS Service
        run: |
          aws ecs update-service --cluster ec2-cluster --service test-5 --force-new-deployment
